#!/bin/bash

# Runs clippy on every package in this repo.
#
# Passes through any extra arguments to each invocation.
#
# Exits non-zero if any clippy invocation exits non-zero,
# but always runs them all.

rc=0
script_args="$@"

MAIN_CRATE=portable-rustls

# XXX TODO UPDATE ENV NAME
# XXX TODO IMPROVE TESTING WITH & WITHOUT x-no-atomic-rc
ALL_FEATURES_EXCEPT_UNSAFE=$(admin/all-features-except unsafe-assume-single-core,x-no-atomic-rc $MAIN_CRATE)

function run_clippy() {
  if ! ( set -x ; cargo clippy --locked "$@" $script_args ) ; then
    rc=$PIPESTATUS
  fi
}

# because examples enable rustls' features, `--workspace --no-default-features` is not
# the same as `--package $MAIN_CRATE --no-default-features` so run it separately
run_clippy --package $MAIN_CRATE --no-default-features --all-targets

# run all workspace members (individually, because we don't want feature unification)
for p in $(admin/all-workspace-members) ; do
  case "$p" in
    $MAIN_CRATE)
      ALL_FEATURES=$ALL_FEATURES_EXCEPT_UNSAFE
      ;;
    *)
      ALL_FEATURES="--all-features"
      ;;
  esac

  run_clippy --package $p $ALL_FEATURES --all-targets
done

# not part of the workspace
run_clippy --manifest-path=fuzz/Cargo.toml --all-features --all-targets

exit $rc
