#!/bin/bash

# Runs clippy on every package in this repo.
#
# Passes through any extra arguments to each invocation.
#
# Exits non-zero if any clippy invocation exits non-zero,
# but always runs them all.

rc=0
script_args="$@"

function run_clippy() {
  if ! ( set -x ; cargo clippy --locked "$@" $script_args ) ; then
    rc=$PIPESTATUS
  fi
}

# because examples enable rustls' features, `--workspace --no-default-features` is not
# the same as `--package portable-rustls --no-default-features` so run it separately
run_clippy --package portable-rustls --no-default-features --all-targets

# run all workspace members (individually, because we don't want feature unification)
for p in $(admin/all-workspace-members) ; do
  case "$p" in
    *)
      # XXX TBD DEFINE MAIN CRATE NAME & RESULT OF admin/all-features-except BEFORE THIS LOOP - ???
      ALL_FEATURES=$(admin/all-features-except unsafe-assume-single-core portable-rustls)
      ;;
  esac

  run_clippy --package $p $ALL_FEATURES --all-targets
done

# not part of the workspace
# XXX TODO FIX MAIN PACKAGE NAME HERE
run_clippy --manifest-path=fuzz/Cargo.toml $(admin/all-features-except unsafe-assume-single-core rustls) --all-targets

exit $rc
