#!/usr/bin/env bash

set -e

MAIN_CRATE=portable-rustls

source <(cargo llvm-cov show-env --export-prefix "$@")
cargo llvm-cov clean --workspace

cargo build --locked --all-targets --all-features
cargo test --locked --all-features
# TEST WITHOUT `fips` [FIPS REMOVED FROM THIS FORK]
cargo test -p $MAIN_CRATE --locked --no-default-features --features tls12,logging,aws_lc_rs,std
cargo test -p $MAIN_CRATE --locked --no-default-features --features tls12,logging,ring,std

# ensure both zlib and brotli are tested, irrespective of their order
cargo test --locked $(admin/all-features-except zlib $MAIN_CRATE)
cargo test --locked $(admin/all-features-except brotli $MAIN_CRATE)

## bogo
cargo test --locked --test bogo -- --ignored --test-threads 1

# provider example unit tests
cargo test --locked --package rustls-provider-example

## provider example tests
cargo test --locked --package rustls-provider-test

cargo llvm-cov report "$@"
