#!/usr/bin/env bash

set -e

MAIN_CRATE=portable-rustls

ALL_FEATURES_EXCEPT_UNSAFE=$(admin/all-features-except unsafe-assume-single-core $MAIN_CRATE)

ALL_FEATURES_EXCEPT_UNSAFE_AND_BROTLI=$(admin/all-features-except unsafe-assume-single-core,brotli $MAIN_CRATE)

# (also need to exclude `unstable-std-extra` which includes `zlib` in first case)
ALL_FEATURES_EXCEPT_UNSAFE_AND_ZLIB=$(admin/all-features-except unsafe-assume-single-core,unstable-std-extra,zlib $MAIN_CRATE)

source <(cargo llvm-cov show-env --export-prefix "$@")
cargo llvm-cov clean --workspace

cargo build --locked --all-targets $ALL_FEATURES_EXCEPT_UNSAFE
cargo test --locked $ALL_FEATURES_EXCEPT_UNSAFE
# TEST WITHOUT `fips` [FIPS REMOVED FROM THIS FORK]
cargo test -p $MAIN_CRATE --locked --no-default-features --features tls12,logging,aws_lc_rs,std
cargo test -p $MAIN_CRATE --locked --no-default-features --features tls12,logging,ring,std

# ensure both zlib and brotli are tested, irrespective of their order
cargo test --locked $ALL_FEATURES_EXCEPT_UNSAFE_AND_ZLIB
cargo test --locked $ALL_FEATURES_EXCEPT_UNSAFE_AND_BROTLI

## bogo
cargo test --locked --test bogo -- --ignored --test-threads 1

# provider example unit tests
cargo test --locked --package rustls-provider-example

## provider example tests
cargo test --locked --package rustls-provider-test

cargo llvm-cov report "$@"
