#!/usr/bin/env bash

set -e

MAIN_CRATE=portable-rustls

source <(cargo llvm-cov show-env --export-prefix "$@")
cargo llvm-cov clean --workspace

# XXX TODO USE $MAIN_CRATE HERE
ALL_FEATURES_EXCEPT_UNSAFE=$(admin/all-features-except unsafe-assume-single-core portable-rustls)

cargo build --locked --all-targets $ALL_FEATURES_EXCEPT_UNSAFE
cargo test --locked $(admin/all-features-except unsafe-assume-single-core rustls) # XXX TODO FIX WITH $MAIN_CRATE
# TEST WITHOUT `fips` [FIPS REMOVED FROM THIS FORK]
cargo test -p $MAIN_CRATE --locked --no-default-features --features tls12,logging,aws_lc_rs,std
cargo test -p $MAIN_CRATE --locked --no-default-features --features tls12,logging,ring,std

# ensure both zlib and brotli are tested, irrespective of their order
# XXX TODO SEPARATE $(admin/all-features-except ...) FOR THESE:
cargo test --locked $(admin/all-features-except zlib,unsafe-assume-single-core $MAIN_CRATE)
cargo test --locked $(admin/all-features-except brotli,unsafe-assume-single-core $MAIN_CRATE)

## bogo
cargo test --locked --test bogo -- --ignored --test-threads 1

# provider example unit tests
cargo test --locked --package rustls-provider-example

## provider example tests
cargo test --locked --package rustls-provider-test

cargo llvm-cov report "$@"
