name: documentation

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    # [REMOVED FROM THIS FORK]
    # branches:
    #   - main
  schedule:
    - cron: '0 18 * * *'

jobs:
  generate:
    name: Generate pre-release documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@nightly

      # [REMOVED FROM THIS FORK]
      # - name: Install zola
      # ...

      - name: Generate version information
        run: |
          echo >tag.html \
            "<script>var version = document.querySelector(\"span.version\");" \
            "version.innerHTML += \"<br>(pre-release docs from <tt>$GITHUB_REF</tt>)\";" \
            "version.title = \"commit $GITHUB_SHA\";" \
            "</script>"

      - name: cargo doc
        # (CARGO DOC WITH ALL FEATURES IN THIS FORK)
        run: cargo doc --locked --all-features --no-deps --package embedded-rustls
        env:
          RUSTDOCFLAGS: -Dwarnings --cfg=docsrs --html-after-content tag.html

      # [REMOVED FROM THIS FORK] Generate other pages for website (etc.)

  # SKIPPING CI JOB IN THIS FORK, AS CONFIGURED BELOW (FOR FUTURE CONSIDERATION)
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    # [CONFIG TO SKIP CI JOB IN THIS FORK]
    # if: github.repository == ...
    if: false
    needs: generate
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
