name: portable-rustls CI

permissions:
  contents: read

on:
  push:
    branches-ignore:
    - 'gh-readonly-queue/**'
    tags:
    - '**'
  pull_request:
  merge_group:
  schedule:
    - cron: '0 18 * * *'

# XXX TBD ??? ???
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.ref }}
  # XXX XXX
  # cancel-in-progress: true

jobs:
  cross-build:
    name: cross build testing
    runs-on: ubuntu-latest
    # XXX TBD KEEP if: here - ???
    if: github.event_name != 'merge_group'
    strategy:
      # XXX KEEP FOR NOW TO SEE EXPECTED BUILD FAILURE ONLY FOR TARGET(S) WITH NO ATOMIC PTR
      fail-fast: false
      matrix:
        target:
          # 32-bit Android (Linux) targets:
          - armv7-linux-androideabi
          # 32-bit target(s) with no atomic ptr:
          - thumbv6m-none-eabi
          # XXX TBD OTHER TARGET(S) - ???
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install rust-toolchain - nightly # XXX TBD for unstable features (...)
        uses: dtolnay/rust-toolchain@nightly
      - name: Install cross (cross-rs) from GitHub
        run: cargo install cross --git https://github.com/cross-rs/cross
      # XXX TBD PARTIAL BUILD WORKAROUNDS - XXX TBD add feature(s) to configure these Cargo updates - ???
      - run: cargo add once_cell -F critical-section -p portable-rustls
      - run: cargo add portable-atomic -F critical-section -p portable-rustls
      - run: cross build --no-default-features --package portable-rustls --target ${{ matrix.target }}
        env:
          RUSTFLAGS: --cfg portable_atomic_unstable_coerce_unsized --cfg unstable_arc
