# NOTE: Despite some difference in focus there may be overlap between this workflow & workflow from upstream RUSTLS in `build.yml`.
# TODO: RECONSIDER & REMOVE any overlapping job(s) from here if possible without impacting what is covered by CI testing.
# FOR FUTURE CONSIDERATION: UPDATE upstream `rustls` workflow in `build.yml` to test with older versions of Rust nightly
name: portable-rustls CI

permissions:
  contents: read

on:
  push:
    branches-ignore:
    - 'gh-readonly-queue/**'
    tags:
    - '**'
  pull_request:
  merge_group:
  schedule:
    - cron: '0 18 * * *'

env:
  # NOTE: `portable-rustls` fork name is REPEATED here in env - TODO avoid repeating if possible
  ALL_FEATURES_EXCEPT_UNSAFE: $(admin/all-features-except unsafe-assume-single-core portable-rustls)
  MAIN_CRATE: portable-rustls

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build with --cfg use_rc_alias & --cfg unstable_portable_atomic_arc
    runs-on: ${{ matrix.os }}
    env:
      RUSTFLAGS: ${{ matrix.cfg-rust-flags }}
    strategy:
      matrix:
        rust:
          - nightly
          # FOR FUTURE CONSIDERATION:
          # - nightly-2024-01-01
          # RUST NIGHTLY version(s) for MSRV - 1.71:
          - nightly-2023-06-01
          # FAILS AT: cargo add once_cell
          # - nightly-2023-05-01
        os:
          - ubuntu-latest
          # FOR FUTURE CONSIDERATION:
          # - macos-latest
          # - windows-latest
        target:
          # 32-BIT TARGET(S) WITH NO ATOMIC PTR:
          - riscv32imc-unknown-none-elf
          - thumbv6m-none-eabi
          # 64-bit target(s) with no std crate - for comparison:
          - aarch64-unknown-none
          - x86_64-unknown-none
        cfg-rust-flags:
          - --cfg unstable_portable_atomic_arc --cfg portable_atomic_unstable_coerce_unsized
          - --cfg use_rc_alias
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install ${{ matrix.rust }} toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}

      # XXX ONLY NEEDED WITH --cfg unstable_portable_atomic_arc ...
      - name: cargo build (debug; no-std; critical-section) # (with no built-in provider)
        run: cargo build -F critical-section --target ${{ matrix.target }}
        working-directory: rustls

      # XXX ONLY NEEDED WITH --cfg unstable_portable_atomic_arc ...
      - name: cargo build (debug; no-std; unsafe-assume-single-core) # (with no built-in provider)
        # TODO: UPDATE to match in case of any more target(s) are added with no atomic ptr
        if: startsWith(matrix.target, 'riscv') || startsWith(matrix.target, 'thumbv6')
        run: cargo build -F unsafe-assume-single-core --target ${{ matrix.target }}
        working-directory: rustls

      # NOTE: BUILD with hashbrown FAILS with no atomic ptr - MISSING SUPPORT in default hasher
      # - name: cargo build (debug; no-std; hashbrown) # (with no built-in provider)
      #   ...

  test:
    # GENERAL NOTE: NO CI TESTING for no-std
    # (CI TESTING with no-std & with no atomic ptr FOR FUTURE CONSIDERATION)
    name: test with --cfg use_rc_alias & --cfg unstable_portable_atomic_arc
    runs-on: ${{ matrix.os }}
    env:
      RUSTFLAGS: ${{ matrix.cfg-rust-flags }}
    strategy:
      matrix:
        rust:
          - nightly
          # TEST with ALL FEATURES back to:
          - nightly-2024-07-01
          # FOR FUTURE CONSIDERATION:
          # TEST with LIMITED FEATURES back to:
          # - nightly-2024-05-01
          # FAILS cargo test: use of unstable library feature in proc-macro2
          # - nightly-2024-04-01
        os:
          - ubuntu-latest
          - macos-latest
          # FOR FUTURE CONSIDERATION:
          # - windows-latest
        cfg-rust-flags:
          - --cfg unstable_portable_atomic_arc --cfg portable_atomic_unstable_coerce_unsized
          - --cfg use_rc_alias
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install ${{ matrix.rust }} toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: cargo test (debug; std) # no built-in provider
        run: cargo test --features std
        working-directory: rustls

      - name: cargo test (debug; unstable-api-all [should cover most if not all non-unsafe features])
        # QUICK WORKAROUND to avoid test issue with Rust nightly-2024-05-...
        if: ${{ !startsWith(matrix.rust, 'nightly-2024-05-') }}
        run: cargo test -F unstable-api-all
        working-directory: rustls

      - name: cargo test (debug; all features except unsafe-assume-single-core)
        # QUICK WORKAROUND to avoid test issue with Rust nightly-2024-05-...
        if: ${{ !startsWith(matrix.rust, 'nightly-2024-05-') }}
        run: cargo test ${{ env.ALL_FEATURES_EXCEPT_UNSAFE }}
        working-directory: rustls

  cross-build:
    name: cross build test with --cfg use_rc_alias & --cfg unstable_portable_atomic_arc
    runs-on: ${{ matrix.os }}
    if: github.event_name != 'merge_group'
    env:
      RUSTFLAGS: ${{ matrix.cfg-rust-flags }}
    strategy:
      matrix:
        rust:
          - nightly
          - nightly-2024-07-01
          # FAILS to install cross (cross-rs) from GitHub
          # - nightly-2024-06-01
        os:
          - ubuntu-latest
          # FOR FUTURE CONSIDERATION:
          # - macos-latest
          # - windows-latest
        target:
          # 32-bit Android (Linux) target(s) - for comparison:
          - armv7-linux-androideabi
          # 32-BIT TARGET(S) WITH NO ATOMIC PTR:
          - thumbv6m-none-eabi
          # additional target(s) - for comparison:
          # NOTE: This could have some overlap with 64-bit ARM-style CPU on macOS CI host;
          # may have similar ARM-style CPU overlap with standard Windows & possibly Linux in the future
          - aarch64-linux-android
        cfg-rust-flags:
          - --cfg unstable_portable_atomic_arc --cfg portable_atomic_unstable_coerce_unsized
          - --cfg use_rc_alias
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install ${{ matrix.rust }} toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
      # TODO: improve performance installing cross-rs with caching - see recent RUSTLS update:
      # - https://github.com/rustls/rustls/pull/2343
      - name: Install cross (cross-rs) from GitHub
        run: cargo install cross --git https://github.com/cross-rs/cross
      - run: cross build --package ${{ env.MAIN_CRATE }} -F critical-section --target ${{ matrix.target }}
      - run: cross build --package ${{ env.MAIN_CRATE }} -F unsafe-assume-single-core --target ${{ matrix.target }}
        # TODO: UPDATE to match in case of any more target(s) are added with no atomic ptr
        if: startsWith(matrix.target, 'thumbv6')

  cross-test:
    # GENERAL NOTE: NO CI TESTING for no-std
    # (CI TESTING with no-std & with no atomic ptr FOR FUTURE CONSIDERATION)
    name: cross-target testing with --cfg use_rc_alias & --cfg unstable_portable_atomic_arc
    runs-on: ${{ matrix.os }}
    if: github.event_name != 'merge_group'
    env:
      RUSTFLAGS: ${{ matrix.cfg-rust-flags }}
    strategy:
      matrix:
        rust:
          - nightly
          - nightly-2024-07-01
          # FAILS to install cross (cross-rs) from GitHub
          # - nightly-2024-06-01
        target:
          # 32-bit Android (Linux) targets:
          - armv7-linux-androideabi
          - i686-linux-android
          - thumbv7neon-linux-androideabi
          # additional target(s):
          # NOTE: This could have some overlap with 64-bit ARM-style CPU on macOS CI host;
          # may have similar ARM-style CPU overlap with standard Windows & possibly Linux in the future
          - aarch64-linux-android
        os:
          - ubuntu-latest
          # FOR FUTURE CONSIDERATION:
          # ...
        cfg-rust-flags:
          - --cfg unstable_portable_atomic_arc --cfg portable_atomic_unstable_coerce_unsized
          - --cfg use_rc_alias
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install ${{ matrix.rust }} toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
      # TODO: improve performance installing cross-rs with caching - see recent RUSTLS update:
      # - https://github.com/rustls/rustls/pull/2343
      - name: Install cross (cross-rs) from GitHub
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Install bindgen feature & CLI for aws-lc-sys (as needed for many cross targets)
        # TODO: improve performance installing bindgen with caching - see recent RUSTLS update:
        # - https://github.com/rustls/rustls/pull/2343
        run: cargo add --dev --features bindgen 'aws-lc-sys@>0.20' --package ${{ env.MAIN_CRATE }} --verbose && cargo install bindgen-cli --verbose
      - run: cross test --package ${{ env.MAIN_CRATE }} --target ${{ matrix.target }}
      - run: cross test -F unstable-api-all --package ${{ env.MAIN_CRATE }} --target ${{ matrix.target }}
      - run: cross test ${{ env.ALL_FEATURES_EXCEPT_UNSAFE }} --package ${{ env.MAIN_CRATE }} --target ${{ matrix.target }}

  full-build:
    # XXX TODO UPDATE AS NEEDED:
    # ensure everything builds together with this build cfg option enabled
    # (with help from exported `Arc` alias)
    name: full build with unstable_portable_atomic_arc cfg
    runs-on: ${{ matrix.os }}
    env:
      RUSTFLAGS: ${{ matrix.cfg-rust-flags }}
    strategy:
      matrix:
        rust:
          - nightly
          # FOR FUTURE CONSIDERATION:
          # try a few Rust nightly versions
          # - nightly-2024-07-01
          # - nightly-2024-01-01
          - nightly-2023-12-01
          # SEEMS TO PANIC
          # - nightly-2023-11-01
          # OK WITH NO FEATURES ENABLED (issue with --all-features due to `zlib`)
          - nightly-2023-10-01
          # KNOWN BUILD FAILURE
          # - nightly-2023-09-01
        os:
          - ubuntu-latest
          # FOR FUTURE CONSIDERATION:
          # - macos-latest
          # - windows-latest
        cfg-rust-flags:
          - --cfg unstable_portable_atomic_arc --cfg portable_atomic_unstable_coerce_unsized
          # XXX TODO FIX & RE-ENABLE:
          # - --cfg use_rc_alias
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install ${{ matrix.rust }} toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: cargo build (debug; no-std) # (with no built-in provider)
        run: cargo build

      - name: cargo build (debug; std; all features except unsafe-assume-single-core)
        # QUICK WORKAROUND TO AVOID BUILD ISSUE WITH RUST NIGHTLY FROM OCTOBER 2023
        if: ${{ !startsWith(matrix.rust, 'nightly-2023-10') }}
        run: cargo build ${{ env.ALL_FEATURES_EXCEPT_UNSAFE }}

  full-test:
    # XXX TODO UPDATE AS NEEDED:
    # test everything builds together with this build cfg option enabled
    # (with help from exported `Arc` alias)
    name: full test with unstable_portable_atomic_arc cfg
    runs-on: ${{ matrix.os }}
    env:
      RUSTFLAGS: ${{ matrix.cfg-rust-flags }}
    strategy:
      matrix:
        rust:
          - nightly
          - nightly-2024-07-01
          # TEST BUILD FAILURE WITH OLDER RUST NIGHTLY VERSIONS
          # - nightly-2024-06-01
          # ...
        os:
          - ubuntu-latest
          # FOR FUTURE CONSIDERATION:
          # - macos-latest
          # - windows-latest
        cfg-rust-flags:
          # XXX TODO FIX & RE-ENABLE:
          - --cfg unstable_portable_atomic_arc --cfg portable_atomic_unstable_coerce_unsized
          # - --cfg use_rc_alias
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install ${{ matrix.rust }} toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: cargo test (debug; no-std) # (with no built-in provider)
        run: cargo test

      - name: cargo test (debug; std; all features except unsafe-assume-single-core)
        run: cargo test ${{ env.ALL_FEATURES_EXCEPT_UNSAFE }}

      - name: cargo test (debug; rustls-provider-example; all features)
        run: cargo test --all-features -p rustls-provider-example

      - name: cargo test (debug; rustls-provider-test; all features)
        run: cargo test --all-features -p rustls-provider-test

  embedded-powerset-build-check:
    name: embedded cargo hack powerset build check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust:
          # Rust nightly REQUIRED for build with unstable_portable_atomic_arc
          - nightly
        os:
          # SKIP FOR NOW:
          # - ubuntu-latest
          - macos-latest
        target:
          # 32-BIT TARGET(S) WITH NO ATOMIC PTR:
          - riscv32imc-unknown-none-elf
          - thumbv6m-none-eabi
        cfg-rust-flags:
          # build with unstable_portable_atomic_arc
          - --cfg unstable_portable_atomic_arc --cfg portable_atomic_unstable_coerce_unsized
          # XXX TODO FIX & RE-ENABLE:
          # build with `alloc::rc::Rc`
          # - --cfg use_rc_alias
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install ${{ matrix.rust }} toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}

      - name: Install cargo hack
        uses: taiki-e/install-action@cargo-hack

      - name: powerset build check
        # IMPORTANT REQUIREMENTS:
        # - EXCLUDE many features that require `std` lib support
        # - INCLUDE EXACTLY ONE of these features:
        #   - critical-section
        #   - unsafe-assume-single-core
        run: >
            cargo hack check
            --package ${{ env.MAIN_CRATE }}
            --feature-powerset
            --no-dev-deps
            --at-least-one-of critical-section,unsafe-assume-single-core
            --exclude-features aws_lc_rs,aws-lc-rs,brotli,prefer-post-quantum,read_buf,ring,std,unstable-api-all,zlib
            --mutually-exclusive-features critical-section,unsafe-assume-single-core
            --target ${{ matrix.target }}
        env:
          RUSTFLAGS: ${{ matrix.cfg-rust-flags }} --deny warnings

  limited-powerset-build-check:
    # XXX TODO UPDATE AS NEEDED:
    name: limited cargo hack powerset build check with unstable_portable_atomic_arc cfg
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust:
          # Rust nightly REQUIRED for build with unstable_portable_atomic_arc
          - nightly
        os:
          # SKIP FOR NOW:
          # - ubuntu-latest
          - macos-latest
        cfg-rust-flags:
          # build with unstable_portable_atomic_arc
          - --cfg unstable_portable_atomic_arc --cfg portable_atomic_unstable_coerce_unsized
          # XXX TODO FIX & RE-ENABLE:
          # build with `alloc::rc::Rc`
          # - --cfg use_rc_alias
          # build with `alloc::sync::Arc`
          - ''
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install ${{ matrix.rust }} toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Install cargo hack
        uses: taiki-e/install-action@cargo-hack

      - name: limited-depth powerset build check
        # USING depth of 2 to test individual feature builds & any combination of 2 features
        # WITHOUT TESTING EXCESSIVE feature combinations for each update
        run: >
            cargo hack check
            --package ${{ env.MAIN_CRATE }}
            --feature-powerset
            --no-dev-deps
            --exclude-features unsafe-assume-single-core
            --group-features aws_lc_rs,aws-lc-rs
            --mutually-exclusive-features custom_provider,aws_lc_rs
            --mutually-exclusive-features custom_provider,ring
            --depth 2
        env:
          RUSTFLAGS: ${{ matrix.cfg-rust-flags }} --deny warnings
